name: Generate API Documentation

on:
  push:
    paths:
      - 'res/**' # This will only trigger on changes to the /res/ folder
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Run Python script to combine YAMLs
      run: |
        mkdir -p output
        python ./redocly/scripts/combine_yamls.py

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

    - name: Install Redocly CLI
      run: npm install -g @redocly/cli

    - name: Generate API documentation with Redocly
      run: |
        redocly build-docs redocly/scripts/master_api_combined.yaml --template redocly/templates/redoc_template.html --output output/redoc-static.html

    - name: Upload Generated HTML as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: redoc-static-${{ steps.date.outputs.date }}
        path: output/redoc-static.html