name: Generate SDKs

on:
  workflow_dispatch:
  push:
    branches:
      - 'release-**'

env:
  SPEC_DIR: ${{ github.workspace }}/specs_preprocessed
  PYTHON_DIR: ${{ github.workspace }}/sdks/python
  BRANCH_NAME: ${{ github.ref_name }}
  SPECIFICATIONS: |
    consolidated-analytics-apis

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    env:
      ORIG_SPEC_DIR: ${{ github.workspace }}/res

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Preprocess OpenAPI specs
        id: preprocess
        run: |
          python3 -m pip install -r $PYTHON_DIR/processing/requirements.txt
          python3 $PYTHON_DIR/processing/spec_preprocessing.py $ORIG_SPEC_DIR $SPEC_DIR

      - name: Upload artifact processed specs
        uses: actions/upload-artifact@v3
        with:
          name: processed-specs-${{ env.BRANCH_NAME }}
          path: ${{ env.SPEC_DIR }}
          retention-days: 7

  generate-python-specification:
    name: Generate Python SDK
    runs-on: ubuntu-latest
    needs: setup-environment
    env:
      PACKAGE_PREFIX: visier.sdk.api
      PACKAGE_DIR: ${{ github.workspace }}/specs_preprocessed
      SDK_REPO_DIR: ${{ github.workspace }}/sdks/generated

    steps:
      - name: Install dependencies
        run: |
          npm install @openapitools/openapi-generator-cli -g
          pip install tox

      - name: Set up Corretto JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'corretto'

      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: processed-specs-${{env.BRANCH_NAME}}
          path: ${{ env.SPEC_DIR }}

      - name: Create a token
        id: create-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: python-sdk

      - name: Checkout Python SDK repository
        uses: actions/checkout@v4
        with:
          repository: visier/python-sdk
          token: ${{ steps.create-token.outputs.token }}
          path: ${{ env.SDK_REPO_DIR }}
          persist-credentials: false

      - name: Generate Python SDK for all specifications
        run: |
          SPECIFICATION_LIST=$(echo $SPECIFICATIONS | tr ',' '\n')
          for specification in $SPECIFICATION_LIST; do
            echo "Processing $specification"
            spec_file="$SPEC_DIR/${specification}.yaml"
            package_name="$PACKAGE_PREFIX.$(echo "$specification" | sed 's/-apis$//; s/-/_/g')"
            output_dir="$SDK_REPO_DIR/src/$package_name"
            spec_version=$(awk '/version:/ {gsub(/"| /, "", $2); print $2}' "$spec_file")
          
            mkdir -p $output_dir
            openapi-generator-cli generate \
              -i "$spec_file" \
              -g python \
              -t $PYTHON_DIR/templates \
              --package-name "$package_name" \
              -o "$output_dir" \
              --skip-validate-spec \
              --additional-properties=packageVersion="$spec_version"
          done

      # Pushing before tests to have the code available for debugging
      - name: Push Python SDK branch
        env:
          GITHUB_TOKEN: ${{ steps.create-token.outputs.token }}
        run: |
          cd $SDK_REPO_DIR
          git config user.name "Visier-Build-Team"
          git config user.email "action@github.com"
          git checkout -b $BRANCH_NAME
          git add *
          git commit -m "Autogenerated Python SDK"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/visier/python-sdk.git
          git push origin $BRANCH_NAME

      - name: Run tests
        run: |
          error_flag=0
          find "$SDK_REPO_DIR/src/" -type d -name "${PACKAGE_PREFIX}*" -print |
          while read -r dir; do
            (cd "$dir" && tox)
            if [ $? -ne 0 ]; then
              error_flag=1
            fi
          done
          exit $error_flag

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ steps.create-token.outputs.token }}
        run: |
          cd $SDK_REPO_DIR
          gh pr create \
            --title "Auto-generated SDK" \
            --body "This PR includes the autogenerated SDKs." \
            --head "$BRANCH_NAME" \
            --base feature/VAN-122988-test
