name: Generate SDKs

on:
  workflow_dispatch:
  push:
    branches:
      - 'release-**'

env:
  SPEC_DIR: ${{ github.workspace }}/specs_preprocessed
  PYTHON_DIR: ${{ github.workspace }}/sdks/python
  VERSION: 0.0.6
  SPECIFICATIONS: |
    consolidated-analytics-apis,
    data-handling-apis,
    data-intake-apis,
    data-version-export-apis,
    direct-data-intake-apis,
    document-search-apis,
    model-query-apis,
    object-configuration-apis,
    permission-management-apis,
    profile-management-apis,
    project-management-apis,
    system-status-apis,
    tenant-management-apis,
    user-management-apis

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    env:
      ORIG_SPEC_DIR: ${{ github.workspace }}/res

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Preprocess OpenAPI specs
        id: preprocess
        run: |
          python3 -m pip install -r $PYTHON_DIR/processing/requirements.txt
          python3 $PYTHON_DIR/processing/spec_preprocessing.py $ORIG_SPEC_DIR $SPEC_DIR
          echo "SPEC_DIR=$SPEC_DIR" >> $GITHUB_ENV

      - name: Upload artifact processed specs
        uses: actions/upload-artifact@v3
        with:
          name: processed-specs-${{ env.VERSION }}
          path: ${{ env.SPEC_DIR }}
          retention-days: 7

  generate-python-specification:
    name: Generate Python SDK
    runs-on: ubuntu-latest
    needs: setup-environment
    env:
      PACKAGE_PREFIX: visier.sdk.api
      PACKAGE_DIR: ${{ github.workspace }}/specs_preprocessed
      SDK_REPO_DIR: ${{ github.workspace }}/sdks/generated

    steps:
      - name: Install dependencies
        run: |
          npm install @openapitools/openapi-generator-cli -g
          pip install tox

      - name: Set up Corretto JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'corretto'

      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: processed-specs-${{env.VERSION}}
          path: ${{ env.SPEC_DIR }}

      - name: Configure git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global url."https://api:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          git config --global user.email "shmalikov@gmail.com"
          git config --global user.name "Shmalikov"

      - name: Create Python SDK version branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ ! -d "$SDK_REPO_DIR" ]; then
            git clone https://github.com/visier/python-sdk.git $SDK_REPO_DIR
          fi
          cd $SDK_REPO_DIR
          git checkout -b versions/$VERSION

      - name: Generate Python SDK for all specifications
        run: |
          SPECIFICATION_LIST=$(echo $SPECIFICATIONS | tr ',' '\n')
          for specification in $SPECIFICATION_LIST; do
            echo "Processing $specification"
            spec_file="$SPEC_DIR/${specification}.yaml"
            package_name="$PACKAGE_PREFIX.$(echo "$specification" | sed 's/-apis$//; s/-/_/g')"
            output_dir="$SDK_REPO_DIR/src/$package_name"

            mkdir -p $output_dir
            openapi-generator-cli generate \
              -i "$spec_file" \
              -g python \
              -t $PYTHON_DIR/templates \
              --package-name "$package_name" \
              -o "$output_dir" \
              --skip-validate-spec \
              --additional-properties=packageVersion="$VERSION"
          done

      # Pushing before tests to have the code available for debugging
      - name: Push Python SDK branch
        run: |
          cd $SDK_REPO_DIR
          ls .
          git add *
          git commit -m "Autogenerated Python SDK version $VERSION"
          git push origin versions/$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          error_flag=0
          find "$SDK_REPO_DIR/src/" -type d -name "${PACKAGE_PREFIX}*" -print |
          while read -r dir; do
            (cd "$dir" && tox)
            if [ $? -ne 0 ]; then
              error_flag=1
            fi
          done
          exit $error_flag

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd $SDK_REPO_DIR
          gh pr create \
            --title "Auto-generated SDK version $VERSION" \
            --body "This PR includes the autogenerated SDKs for version $VERSION." \
            --head "versions/$VERSION" \
            --base feature/VAN-122988-test