on: [ workflow_call ]

env:
  SPEC_DIR: ${{ github.workspace }}/specs_preprocessed
  PYTHON_DIR: ${{ github.workspace }}/sdks/python
  VERSION: 0.0.1

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    env:
      ORIG_SPEC_DIR: ${{ github.workspace }}/res
      PREPROCESS: true

    steps:
      - name: Set up GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          gh pr create --repo visier/python-sdk \
            --title "Automated PR: Update from versions/0.0.1" \
            --body "This PR merges updates from the versions/0.0.1 branch into the main branch." \
            --head ${{ github.repository_owner }}:versions/0.0.1 \
            --base main \
            --assignee Shmalikov \
            --label "automation"