on: [workflow_call]

jobs:
  test-java-driver:
    name: Test Java drivers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        driver: ["authentication-apis", "model-query-apis"]
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of OpenAPI Generator
        run:
          npm install @openapitools/openapi-generator-cli -g
      - name: Set up Corretto JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'corretto'
            architecture: x64
      - name: Generate client wrapper for ${{ matrix.driver }} in Java ${{ matrix.version }}
        run: |
          mkdir -p ${{ github.workspace }}/sdks/drivers/java/${{ matrix.driver }}
          npx @openapitools/openapi-generator-cli generate -i ${{ github.workspace }}/res/${{ matrix.driver}}.yaml -g java -o ${{ github.workspace }}/sdks/drivers/java/${{ matrix.driver }}
      - name: Run Java tests for ${{ matrix.driver }}
        run: |
          echo "Does nothing for the time being"

