on: [workflow_call]

jobs:
  test-python-driver:
    name: Test Python drivers
    runs-on: ubuntu-latest
    container:
      image: openapitools/openapi-generator-cli:latest
    strategy:
      max-parallel: 1
      matrix:
#        driver: ["authentication-apis", "model-query-apis", "direct-data-intake-apis"]
#        version: ["3.8", "3.9", "3.10", "3.11"]
        driver:
          - spec : "authentication-apis"
            package: "visier.authentication"



        version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
#      - name: Install the latest version of OpenAPI Generator
#        run:
#          npm install @openapitools/openapi-generator-cli -g
#      - name: Set up Corretto JDK 11
#        uses: actions/setup-java@v3
#        with:
#            java-version: '11'
#            distribution: 'corretto'
#            architecture: x64
      - name: Generate client wrapper for ${{ matrix.driver }} in Python ${{ matrix.version }}
        run: |
          sdk_dir="${{ github.workspace }}/sdks/drivers/python${{ matrix.version }}/${{ matrix.driver.spec }}"
          mkdir -p $sdk_dir
          docker-entrypoint.sh generate -i "${{ github.workspace }}/res/${{ matrix.driver.spec}}.yaml" -g python -o $sdk_dir --package-name ${{ matrix.driver.package }}
#      - name: Setup Python ${{ matrix.version }}
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.version }}
#      - name: Run tests with Python ${{ matrix.version }}
#        run: |
#          cd ${{ github.workspace }}/sdks/drivers/python${{ matrix.version }}/${{ matrix.driver }}
#          python3 -m venv venv
#          source venv/bin/activate
#          pip install -r requirements.txt
#          pip install -r test-requirements.txt
#          pytest

